### ISSUE TITLE
Re-activate travis

### ISSUE THREAD

**Issue by ManfredKarrer** [bisq-network/bisq#346]
Travis has infrastructure updates (sudo: false) and beside that the support for javaFX seems broken 
([ERROR] location: class com.sun.javafx.tk.quantum.QuantumToolkit)
Need investigation how to fix that.

**Comment by jonathancross** [comment]
Is this of use?

https://docs.travis-ci.com/user/languages/java/#Testing-Against-Multiple-JDKs

> Of note: OracleJDK 8 and JavaFX  projects may need to update to the latest available version from a repository. This can be accomplished by adding the following lines from [this issue comment](https://github.com/travis-ci/travis-ci/issues/3259#issuecomment-130860338) to your .travis.yml:

```yaml
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
 ```
